/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Moraes Bueno
 */
public class newMemoria extends javax.swing.JFrame {

    /**
     * Creates new form menuMemoria
     */
    public newMemoria() {
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLevel = new javax.swing.ButtonGroup();
        grupoquantia = new javax.swing.ButtonGroup();
        rbFacil = new javax.swing.JRadioButton();
        rbMedio = new javax.swing.JRadioButton();
        rbDificil = new javax.swing.JRadioButton();
        lblDificuldade = new javax.swing.JLabel();
        lblQtdPecas = new javax.swing.JLabel();
        rbDoze = new javax.swing.JRadioButton();
        rbVinte = new javax.swing.JRadioButton();
        rbVinteQuatro = new javax.swing.JRadioButton();
        rbTrinta = new javax.swing.JRadioButton();
        btnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo - Memória Ambiental");
        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png")).getImage());

        grupoLevel.add(rbFacil);
        rbFacil.setText("Fácil");
        rbFacil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbFacilFocusGained(evt);
            }
        });

        grupoLevel.add(rbMedio);
        rbMedio.setText("Médio");

        grupoLevel.add(rbDificil);
        rbDificil.setText("Dificil");

        lblDificuldade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDificuldade.setForeground(new java.awt.Color(0, 51, 51));
        lblDificuldade.setText("Escolha a dificuldade do jogo!");

        lblQtdPecas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQtdPecas.setForeground(new java.awt.Color(0, 51, 51));
        lblQtdPecas.setText("Com quantas peças deseja jogar?");

        grupoquantia.add(rbDoze);
        rbDoze.setText("12 Peças");
        rbDoze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDozeActionPerformed(evt);
            }
        });

        grupoquantia.add(rbVinte);
        rbVinte.setText("20 Peças");
        rbVinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVinteActionPerformed(evt);
            }
        });

        grupoquantia.add(rbVinteQuatro);
        rbVinteQuatro.setText("24 Peças");

        grupoquantia.add(rbTrinta);
        rbTrinta.setText("30 Peças");

        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbFacil)
                        .addGap(29, 29, 29)
                        .addComponent(rbMedio)
                        .addGap(29, 29, 29)
                        .addComponent(rbDificil))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDoze)
                            .addComponent(rbVinte))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbTrinta)
                            .addComponent(rbVinteQuatro)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnJogar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQtdPecas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDificuldade)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFacil)
                    .addComponent(rbMedio)
                    .addComponent(rbDificil))
                .addGap(18, 18, 18)
                .addComponent(lblQtdPecas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDoze)
                    .addComponent(rbVinteQuatro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVinte)
                    .addComponent(rbTrinta))
                .addGap(18, 18, 18)
                .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        MemoriaGame objMemoriaJava;
        try {
            if (rbFacil.isSelected() && rbDoze.isSelected()) {
                objMemoriaJava = new MemoriaGame(12, 3, "Fácil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbFacil.isSelected() && rbVinte.isSelected()) {
                objMemoriaJava = new MemoriaGame(20, 5, "Fácil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbFacil.isSelected() && rbVinteQuatro.isSelected()) {
                objMemoriaJava = new MemoriaGame(24, 5, "Fácil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbFacil.isSelected() && rbTrinta.isSelected()) {
                objMemoriaJava = new MemoriaGame(30, 7, "Fácil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbMedio.isSelected() && rbDoze.isSelected()) {
                objMemoriaJava = new MemoriaGame(12, 5, "Médio");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbMedio.isSelected() && rbVinte.isSelected()) {
                objMemoriaJava = new MemoriaGame(20, 6, "Médio");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbMedio.isSelected() && rbVinteQuatro.isSelected()) {
                objMemoriaJava = new MemoriaGame(24, 7, "Médio");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbMedio.isSelected() && rbTrinta.isSelected()) {
                objMemoriaJava = new MemoriaGame(30, 11, "Médio");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbDificil.isSelected() && rbDoze.isSelected()) {
                objMemoriaJava = new MemoriaGame(12, 8, "Dificil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbDificil.isSelected() && rbVinte.isSelected()) {
                objMemoriaJava = new MemoriaGame(20, 10, "Dificil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbDificil.isSelected() && rbVinteQuatro.isSelected()) {
                objMemoriaJava = new MemoriaGame(24, 12, "Dificil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

            if (rbDificil.isSelected() && rbTrinta.isSelected()) {
                objMemoriaJava = new MemoriaGame(30, 18, "Dificil");
                objMemoriaJava.setVisible(true);
                this.hide();
            }

        } catch (Exception ex) {
            // JOptionPane.showConfirmDialog(this, ex.toString(), null, WIDTH);
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void rbDozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDozeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDozeActionPerformed

    private void rbVinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVinteActionPerformed

    private void rbFacilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbFacilFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFacilFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new newMemoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.ButtonGroup grupoLevel;
    private javax.swing.ButtonGroup grupoquantia;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblQtdPecas;
    private javax.swing.JRadioButton rbDificil;
    private javax.swing.JRadioButton rbDoze;
    private javax.swing.JRadioButton rbFacil;
    private javax.swing.JRadioButton rbMedio;
    private javax.swing.JRadioButton rbTrinta;
    private javax.swing.JRadioButton rbVinte;
    private javax.swing.JRadioButton rbVinteQuatro;
    // End of variables declaration//GEN-END:variables
}
